name: Python application

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # Keep running other matrix jobs even if one fails
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.13"]
        test-file: [
          "tests/test_pipeline.py", 
          "tests/test_run_facial_landmarks_prediction.py", 
          "tests/test_run_prepare_data_to_arff.py",
          "tests/test_utils.py"
        ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v --cov=./ ${{ matrix.test-file }}
